version: '3'

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: clickadilla_test
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www
    user: "1000:1000"
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  composer:
    image: composer:latest
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: "composer"
    user: "1000:1000"
    networks:
      - backend

networks:
  backend:
